OnlineShop/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from OnlineShop import settings
from users.views import LoginView

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'OnlineShop.views.home', name='home'),
                       # url(r'^OnlineShop/', include('OnlineShop.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^logout$', 'users.views.sign_out', name='logout'),
                       url(r'^login$', LoginView.as_view(), name='login'),
                       url(r'^register$', 'users.views.register', name='register'),
                       url(r'^city/change/(?P<city_id>\d+)/$', 'users.views.change_city', name='city_change'),
                       url(r'^good/like/(?P<good_id>\d+)/$', 'users.views.like_good', name='like_good'),
                       url(r'^good/review/(?P<good_id>\d+)/$', 'users.views.leave_review', name='leave_review'),

                       url(r'^$', 'shopCatalog.views.index', name='index'),

                       url(r'^add$', 'shopCatalog.views.addGood', name='add_good'),

                       url(r'^catalog$', 'shopCatalog.views.filter_catalog', name='catalog'),

                       url(r'^good/(?P<good_id>\d+)/$', 'shopCatalog.views.render_good', name='good_page'),

                       url(r'^watched/$', "users.views.render_watched", name='watched_goods'),

                       url(r'^good/(?P<good_id>\d+)/add$', 'shopCatalog.views.add_to_cart', name='add_to_cart'),

                       url(r'^cart/$', "shopCatalog.views.render_cart", name='cart'),

                       url(r'^cart/delete/(?P<good_id>\d+)$', "shopCatalog.views.delete_from_cart",
                           name='delete_from_cart'),

                       url(r'^order/make$', "shopCatalog.views.render_make_order", name='make_order'),

                       url(r'^order/approve$', "shopCatalog.views.make_order", name='approve_order'),

                       url(r'^catalog/ajax$', "shopCatalog.views.filter_catalog", name='catalog_ajax'),

                       url(r'^contacts/$', TemplateView.as_view(template_name="contacts.html"), name='contacts'),

                       url(r'^site/', include('admin.urls', namespace='site_admin')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'OnlineShop.views.home', name='home'),
    # url(r'^OnlineShop/', include('OnlineShop.foo.urls')),

    url(r'^categories$', 'admin.views.render_manage_category', name='manage_category'),
)

templates/contacts.html
{% extends "mainTemplate_new.html" %}
{% block body_block %}
        <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contacts</h1>
        </div>
    </div>
    <h1>And now you exactly know who you have to beat on the fingers for this code =)</h1>
    <p>+79274205286</p>
    <p>praim199524@gmail.com</p>
{% endblock %}

templates/mainPage.html
{% extends 'mainTemplate_new.html' %}
{% load static %}
{% block title %} Main page title {% endblock %}
{% block custom_head %}
    <link href="{% static "css/main-page.css" %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block body_block %}
    <div class="row carousel-holder">

        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    {% for action in actions %}
                        <div class="item {% if forloop.counter0 == 0 %}active {% endif %}">
                            <a href="{{ action.action_url }}">
                                <img class="slide-image" src="{{ action.imageUrl }}">
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Best selling goods
            </h3>
        </div>
        {% for good in goods %}
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="http://placehold.it/320x150" alt="">

                    <div class="caption">
                        <div class="row">
                            <div class="col-md-9">
                                <strong><a href="{% url 'good_page' good.id %}">{{ good.name|slice:"50" }}</a>
                                </strong>
                            </div>
                            <div class="col-md-3">
                                <h4 class="pull-right">${{ good.price|stringformat:"d" }}</h4>
                            </div>
                        </div>
                        <p>{{ good.longName }}</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>

                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}

templates/mainTemplate.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>{% block title %} My site title {% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/static/js/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</head>

<body>
<table width="920" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr>
        <td height="25">&nbsp;</td>
    </tr>
    <tr>
        <td height="77" class="header">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td width="28%" align="left"><a href="http://www.templatesfreelance.com/"><img
                            src="/static/images/logo.jpg"
                            alt="" width="262"
                            height="77"
                            border="0"></a></td>
                    <td width="72%" align="right">
                        {% if user.is_authenticated %}
                            Welcome, {{ user.username }}. &nbsp;&nbsp;
                            <a href="{% url 'logout' %}">Logout</a> &nbsp;&nbsp;
                            <a href="{% url 'cart' %}">Cart</a> &nbsp;&nbsp;
                        {% else %}
                            <a href="{% url 'login' %}">Login</a> &nbsp;&nbsp;
                            <a href="{% url 'register' %}">Register</a> &nbsp;&nbsp;
                        {% endif %}
                        <a href="{% url 'contacts' %}">Contacts</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td height="38" class="menu">

            <div class="menuLs">
                <ul>
                    <li><a href="/" id="WhiteColor">Home</a></li>
                    <li><a href="http://www.templatesfreelance.com/" id="WhiteColor">News</a></li>
                    <li><a href="http://www.templatesfreelance.com/" id="WhiteColor">Reviews</a></li>
                    <li><a href="{% url 'catalog' %}" id="WhiteColor">Goods catalog</a></li>
                    <li><a href="{% url 'add_good' %}" id="WhiteColor">Add good</a></li>
                    <li><a href="{% url 'watched_goods' %}" id="WhiteColor">User watched goods</a></li>
                    <li><a href="{% url 'contacts' %}" id="WhiteColor">Contacts</a></li>
                    <li><a href="{% url 'site_admin:manage_category' %}" id="WhiteColor">Manage categories</a></li>
                </ul>
            </div>
        </td>
    </tr>
    <tr>
        <td height="20">&nbsp;</td>
    </tr>
    <tr>
        <td>
            {% block body_block %}
                default text
            {% endblock %}
        </td>
    </tr>
    <tr>
        <td height="20">&nbsp;</td>
    </tr>
    <tr>
        <td align="center"><a href="http://www.templatesfreelance.com/"><img src="/static/images/footer.gif" alt=""
                                                                             width="920"
                                                                             height="4" border="0"></a></td>
    </tr>
    <tr>
        <td height="60" align="center"><a href="http://www.templatesfreelance.com/">Home</a> | <a
                href="http://www.templatesfreelance.com/">News</a> | <a href="http://www.templatesfreelance.com/">Reviews</a>
            | <a href="http://www.templatesfreelance.com/">How-To's</a> | <a href="http://www.templatesfreelance.com/">Downloads</a>
            | <a href="http://www.templatesfreelance.com/">Shop &amp; Compare</a> | <a
                    href="http://www.templatesfreelance.com/">Apps</a> | <a href="http://www.templatesfreelance.com/">Business
                Center</a> | <a href="http://www.templatesfreelance.com/">FAQ</a> | <a
                    href="http://www.templatesfreelance.com/">Contact Us</a><br>
            TemplatesFreeLance.com &copy; copyright 2012 - <a href="http://www.templatesfreelance.com/">Web Page
                Templates </a></td>
    </tr>
</table>
</body>
</html>

templates/mainTemplate_new.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} My site title {% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/main.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token }}";
        {% if min_price %} var min_price = {{ min_price }}; {% endif %}
        {% if max_price %} var max_price = {{ max_price }}; {% endif %}
        {% if c_price_l %} var c_price_l = {{ c_price_l }}; {% endif %}
        {% if c_price_r %} var c_price_r = {{ c_price_r }}; {% endif %}
    </script>
    <script type="text/javascript" src="/static/js/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>

    {% block custom_head %}
    {% endblock %}

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Django shop</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="navbar-text">Welcome, <span class="navbar-link">{{ user.username }} </span></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li><a href="{% url 'cart' %}">Cart</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
                <li><a href="{% url 'catalog' %}" id="WhiteColor">Catalog</a></li>
                <li><a href="{% url 'watched_goods' %}" id="WhiteColor">Watched</a></li>
                <li><a href="{% url 'add_good' %}" id="WhiteColor">Add good</a></li>
                <li><a href="{% url 'site_admin:manage_category' %}" id="WhiteColor">Manage categories</a></li>
                <li><a href="{% url 'contacts' %}" id="WhiteColor">Contacts</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-md-3">
            {#            <p class="lead">Django Shop</p>#}
            <p>
                <button type="button" class="btn btn-default center-block" id="city-btn">{{ a_city.name }}&nbsp;v
                </button>
            </p>
            <div class="list-group">
                <a href="/catalog" data-id="-1" class="list-group-item js-catalog active">All</a>
                {% for category in categories %}
                    <a href="/catalog?catalog={{ category.id }}" data-id="{{ category.id }}"
                       class="list-group-item js-catalog">{{ category.name }}</a>
                {% endfor %}
            </div>
            <div class="col-md-12">
                {% block custom_left_block %}
                {% endblock %}
            </div>
        </div>

        <div class="col-md-9">

            {% block body_block %}
                default text
            {% endblock %}

        </div>

    </div>

</div>
<!-- /.container -->

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>

<div id="city_modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                {% if a_city %}
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                {% endif %}
                <h4 class="modal-title">Change city</h4>
            </div>
            <div class="modal-body">
                {% if a_city %}
                    <p>Do you want to change your city?</p>
                {% else %}
                    <p class="text text-warning">Please, select your city.</p>
                {% endif %}
                <div class="list-group">
                    {% for city in cities %}
                        <a href="/city/change/{{ city.id }}"
                           class="list-group-item {% if city.id == a_city.id %}active{% endif %}">{{ city.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                {% if a_city %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                {% endif %}
                {#                <button type="button" class="btn btn-primary">Save changes</button>#}
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#city-btn").on('click', function () {
        $("#city_modal").modal('show');
        return false;
    });
    {% if not a_city %}
        $("#city_modal").modal({
            backdrop: 'static',
            keyboard: false
        });
        $("#city_modal").modal('show');
    {% endif %}
</script>
<!-- /.container -->
</body>
</html>